### ISSUE TITLE
Remove sprite after text

### ISSUE THREAD

**Issue by Jademalo** [zenzoa/mosi#37]
Having a small issue, not sure if this is intentional in the design of the framework or an issue with what I'm doing.

```My brother was asking after me?
I should go see him.
{remove-sprite}
{place-sprite floor master-3 room-2-1 7 7}
```

The intention with this was to remove the sprite after the dialogue had finished. However, everything seems to run at once, and he disappears immediately on talking to him.

Is there any way to delay removing the sprite until after the text box has been closed?

Thanks

**Comment by zenzoa** [comment]
Good point! I'll take a look and see what I can do.

**Comment by zenzoa** [comment]
The way I've got it set up right now, it runs all the scripts and puts aside the dialog parts, then displays the dialog. So either I restructure the code so that it runs scripts as they appear; or I could add an {after}...{/after} function that explicitly runs the contents when the dialog is done. The first option is much more difficult to implement, but also probably more intuitive and has the benefits of letting you perform a sequence of actions during the course of the dialog.

**Comment by Jademalo** [comment]
I'd say if you're up to it, the first option would be really neat and very intuitive.

The thing I'm working on has a lot of things structured weirdly in order to trick the player into performing inputs to "advance" the scripts at the right times, like invisible tiles and traps where I spawn walls around the player during one dialogue, so when they try to move after the first section it plays the next section.

Another potential workaround aside from {after} could be something like {retrigger}, where everything before the retrigger runs, then everything after, then everything after etc etc. So one on push event with retriggers gives a similar effect to 3 on push triggers in a row.

**Comment by zenzoa** [comment]
Ok, came up with (I hope) a relatively elegant solution to run functions where they occur in dialog instead of all at the start. I haven't tested it super thoroughly, but so far it seems to work - and avoids messy workarounds!

I also refined dialog interaction slightly, by removing the ability to skip to the end, and adding a very slight delay at the end of the page before you can move to the next dialog/close the dialog - this prevents the player (which is usually me) from accidentally missing dialog by pressing the arrow keys too enthusiastically, and also makes sure any scripts tied to dialog speed won't happen too fast.

Now I'm thinking I need a {delay} function to add dramatic pauses in speech or further control script timing...

**Comment by Jademalo** [comment]
Oh wow awesome, that was quick!
Couple of things I've noticed - 

- After moving the player with {move-avatar}, the white square text box advance thing appears and requires another input to clear, even if there's no text associated with it.
- The delay at the end of pages to prevent skipping is great (I did that way too much as well lol), but not being able to skip (or at the very least influence the speed) feels quite sluggish. 
- The following code no longer seems to work, and I'm not sure why;

```
{inc-var lift-floor}

{if {eq {var lift-floor} 1}}
{if {not {eq {item-count office-pass} 1}}}
{inc-var lift-floor}
{/if}
{/if}

{if {eq {var lift-floor} 2}}
{if {not {var server-access}}}
{inc-var lift-floor}
{/if}
{/if}

{if {eq {var lift-floor} 4}}
{set-var lift-floor 0}
{/if}


{if {eq {var lift-floor} 3}}
{wavy}L3 - Queen CEO's Office{/wavy}
{/if}

{if {eq {var lift-floor} 2}}
{wavy}L2 - Server Room{/wavy}
{/if}

{if {eq {var lift-floor} 1}}
{wavy}L1 - Office{/wavy}
{/if}

{if {eq {var lift-floor} 0}}
{wavy}Ground - Lobby{/wavy}
{/if}
```

I added some debug printouts to the above, and it seemed like everything was happening in a weird order.
The {inc-var} at the top seemingly didn't run until the script had finished the dialogue, so all of the other logic was running as if it hadn't incremented. But then after the dialogue finished, it did increment. 

What's even weirder though is it doesn't matter where I put the var-increment, it will always only increment after everything else has been processed. Even if I encapsulate it in an always true if statement like
```
{if {eq 1 1}}
{inc-var lift-floor}
{/if}
```
Honestly, I'm not 100% sure what's going on here, but basically all of the logic seems to be running before taking into account any changes in variables that the logic uses, and then at the end things are incrementing. 
This worked in the older version, and theoretically should work if everything was being done sequentially. My guess is that it's only paying attention to what the variables were when the script was initiated, rather than what they would be at that point in the script.

**Comment by zenzoa** [comment]
Ah yes... that's because I did something silly and had the {if} statements evaluate at the beginning of the script, and the rest happens in-line with the dialog. I'll change that! (And then look into the other things)

**Comment by Jademalo** [comment]
Haha, glad you know what caused it! Hopefully it's a quick and easy fix.

Thanks again for all of this, I've really been thoroughly enjoying making my silly little game with this framework!

**Comment by zenzoa** [comment]
I reverted the delayed script functionality for now, just so it doesn't break things while I figure out a better solution. Glad you're enjoying it so far! :D

**Comment by zenzoa** [comment]
Phew! I rewrote the dialog system to draw and evaluation functions/expressions as it goes along, instead of preparing the dialog ahead of time. It's probably a little buggy still, but give it a shot. (Pro tip: you can use {p} page breaks if you want a certain function to only run after the player has closed the dialog, such as "And now, farewell{p}{remove-sprite}")

**Comment by Jademalo** [comment]
Awesome, that sounds great!
I'll give it a shot tonight and let you know how I get on.

Thanks again!

**Comment by Jademalo** [comment]
Good news, it all seems to work perfectly!

The only thing I've noticed is the textbox pause still happens when a textless script is run, such as touching a sprite that moves you somewhere else. It auto-clears thankfully, but it is a bit strange.

Functions and expressions all seemed to work exactly how you would expect them to, so that's all fantastic.

Thank you so much for implementing this, it really let me add that last little layer of polish to my silly little game!
